agency/urls.py
from django.urls import path
from agency.views import (
    index,
    TopicListView,
    NewspaperListView,
    PublisherListView,
    NewspaperDetailView,
    PublisherDetailView,
    TopicCreateView,
    TopicUpdateView,
    TopicDeleteView,
    NewspaperCreateView,
    NewspaperUpdateView,
    NewspaperDeleteView
)

urlpatterns = [
    path("", index, name="index"),
    path(
        "topics/",
        TopicListView.as_view(),
        name="topic-list",
    ),
    path(
        "topics/create/",
        TopicCreateView.as_view(),
        name="topic-create",
    ),
    path(
        "topics/<int:pk>/update/",
        TopicUpdateView.as_view(),
        name="topic-update",
    ),
    path(
        "topics/<int:pk>/delete/",
        TopicDeleteView.as_view(),
        name="topic-delete",
    ),
    path(
        "articles/",
        NewspaperListView.as_view(),
        name="newspaper-list",
    ),
    path(
        "articles/create/",
        NewspaperCreateView.as_view(),
        name="newspaper-create",
    ),
    path(
        "articles/<int:pk>/update/",
        NewspaperUpdateView.as_view(),
        name="newspaper-update",
    ),
    path(
        "articles/<int:pk>/delete/",
        NewspaperDeleteView.as_view(),
        name="newspaper-delete",
    ),
    path(
        "articles/<int:pk>/",
        NewspaperDetailView.as_view(),
        name="newspaper-detail",
    ),
    path(
        "publishers/",
        PublisherListView.as_view(),
        name="publisher-list",
    ),
    path(
        "publishers/<int:pk>/",
        PublisherDetailView.as_view(),
        name="publisher-detail",
    ),
]

app_name = "agency"

newspaper_agency/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
   path("admin/", admin.site.urls),
   path("", include("agency.urls", namespace="agency")),
   path('accounts/', include('django.contrib.auth.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

agency/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse


class Topic(models.Model):
    name = models.CharField(max_length=255, unique=True)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name


class Publisher(AbstractUser):
    years_of_experience = models.IntegerField(blank=True, null=True)

    class Meta:
        verbose_name = "publisher"
        verbose_name_plural = "publishers"

    def __str__(self):
        return f"{self.username} ({self.first_name} {self.last_name})"

    def get_absolute_url(self):
        return reverse("agency:publisher-detail", kwargs={"pk": self.pk})


class Newspaper(models.Model):
    title = models.CharField(max_length=255)
    content = models.TextField()
    published_date = models.DateTimeField(auto_now_add=True)
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    publishers = models.ManyToManyField(Publisher, related_name="newspapers")

    class Meta:
        ordering = ["-published_date"]

    def __str__(self):
        return self.title

agency/forms.py
from django import forms
from django.contrib.auth import get_user_model

from agency.models import Topic, Newspaper


class TopicForm(forms.ModelForm):
    cancel = forms.BooleanField(required=False, initial=False)
    class Meta:
        model = Topic
        fields = ["name"]


class NewspaperForm(forms.ModelForm):
    publishers = forms.ModelMultipleChoiceField(
        queryset=get_user_model().objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )
    cancel = forms.BooleanField(required=False, initial=False)


    class Meta:
        model = Newspaper
        fields = "__all__"
        widgets = {
             "title": forms.TextInput(
                attrs={"placeholder": "Enter article title"}
            ),
            "content": forms.Textarea(
                attrs={"rows": 15,
                       "placeholder": "Insert content of the article"
                       }
            )
        }


class PublisherUsernameSearchForm(forms.Form):
    Username = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by username.."})
    )


class NewspaperTitleSearchForm(forms.Form):
    title = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by title.."})
    )


class TopicNameSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by topic name.."})
    )

agency/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.views import generic
from django.views.generic.base import ContextMixin

from agency.forms import (
    TopicForm,
    NewspaperForm,
    TopicNameSearchForm,
    NewspaperTitleSearchForm,
    PublisherUsernameSearchForm
)
from agency.models import Topic, Newspaper, Publisher


def index(request):
    """View function for the home page of the site."""

    num_topics = Topic.objects.count()
    num_newspapers = Newspaper.objects.count()
    num_publishers = Publisher.objects.count()

    num_visits = request.session.get("num_visits", 0)
    request.session["num_visits"] = num_visits + 1

    context = {
        "num_topics": num_topics,
        "num_newspapers": num_newspapers,
        "num_publishers": num_publishers,
        "num_visits": num_visits + 1,
    }

    return render(request, "agency/index.html", context=context)


class TopicListView(LoginRequiredMixin, generic.ListView):
    model = Topic
    context_object_name = "topic_list"
    template_name = "agency/topic_list.html"
    queryset = Topic.objects.all()

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(TopicListView, self).get_context_data(**kwargs)
        name = self.request.GET.get("name", "")
        context["search_form"] = TopicNameSearchForm(initial={"name": name})
        return context

    def get_queryset(self):
        form = TopicNameSearchForm(self.request.GET)

        if form.is_valid():
            return self.queryset.filter(
                name__icontains=form.cleaned_data["name"]
            )


class TopicCreateView(LoginRequiredMixin, generic.CreateView):
    model = Topic
    fields = "__all__"
    success_url = reverse_lazy("agency:topic-list")

    def form_valid(self, form):
        if self.request.POST.get("action") == "create":
            form.save()
        return super().form_valid(form)

    def post(self, request, *args, **kwargs):
        if "cancel" in request.POST:
            return HttpResponseRedirect(reverse("agency:topic-list"))
        else:
            return super().post(request, *args, **kwargs)


class TopicUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Topic
    form_class = TopicForm
    success_url = reverse_lazy("agency:topic-list")

    def get_initial(self):
        initial = super().get_initial()
        if self.object.name:
            initial["cancel"] = True
        return initial

    def form_valid(self, form):
        if (self.request.POST.get("action") == "update"
                and "cancel" in self.request.POST):
            return HttpResponseRedirect(self.get_success_url())
        return super().form_valid(form)


class TopicDeleteView(LoginRequiredMixin, generic.DeleteView, ContextMixin):
    model = Topic
    success_url = reverse_lazy("agency:topic-list")


class NewspaperListView(LoginRequiredMixin, generic.ListView):
    model = Newspaper
    paginate_by = 5
    queryset = Newspaper.objects.select_related("topic")

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(NewspaperListView, self).get_context_data(**kwargs)
        title = self.request.GET.get("title", "")
        context["search_form"] = NewspaperTitleSearchForm(
            initial={"title": title}
        )
        return context

    def get_queryset(self):
        form = NewspaperTitleSearchForm(self.request.GET)

        if form.is_valid():
            return self.queryset.filter(
                title__icontains=form.cleaned_data["title"]
            )


class NewspaperDetailView(LoginRequiredMixin, generic.DetailView):
    model = Newspaper


class NewspaperCreateView(LoginRequiredMixin, generic.CreateView):
    model = Newspaper
    form_class = NewspaperForm
    success_url = reverse_lazy("agency:newspaper-list")

    def form_valid(self, form):
        if self.request.POST.get("action") == "create":
            form.save()
        return super().form_valid(form)

    def post(self, request, *args, **kwargs):
        if "cancel" in request.POST:
            return HttpResponseRedirect(reverse("agency:newspaper-list"))
        else:
            return super().post(request, *args, **kwargs)


class NewspaperUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Newspaper
    form_class = NewspaperForm

    def get_success_url(self):
        return reverse_lazy(
            "agency:newspaper-detail",
            kwargs={"pk": self.object.pk}
        )

    def get_initial(self):
        initial = super().get_initial()
        if self.object:
            initial["cancel"] = True
        return initial

    def form_valid(self, form):
        if (self.request.POST.get("action") == "update"
                and "cancel" in self.request.POST):
            return HttpResponseRedirect(self.get_success_url())
        return super().form_valid(form)


class NewspaperDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Newspaper
    success_url = reverse_lazy("agency:newspaper-list")


class PublisherListView(LoginRequiredMixin, generic.ListView):
    model = Publisher
    paginate_by = 5
    queryset = Publisher.objects.all()

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(PublisherListView, self).get_context_data(**kwargs)
        username = self.request.GET.get("Username", "")
        context["search_form"] = PublisherUsernameSearchForm(
            initial={"Username": username}
        )
        return context

    def get_queryset(self):
        form = PublisherUsernameSearchForm(self.request.GET)

        if form.is_valid():
            return self.queryset.filter(
                username__icontains=form.cleaned_data["Username"]
            )


class PublisherDetailView(LoginRequiredMixin, generic.DetailView):
    model = Publisher
    queryset = Publisher.objects.all().prefetch_related("newspapers__topic")

templates/agency/index.html
{% extends "base.html" %}


{% block content %}
 <header class="header-2">
   <div class="page-header min-vh-75 relative" style="background-image: url('{{ ASSETS_ROOT }}/img/bg-main.jpg')">
     <span class="mask bg-gradient-dark opacity-4"></span>
     <div class="container">
       <div class="row">
         <div class="col-lg-7 text-center mx-auto">
           <h1 class="text-white pt-3 mt-n5">Newspaper agency</h1>
           <p class="lead text-white mt-3">Your Daily Dose of Information</p>
         </div>
       </div>
     </div>
   </div>
 </header>
 <div class="card card-body blur shadow-blur mx-3 mx-md-4 mt-n9">
   <section class="pt-3 pb-6" id="count-stats">
     <div class="container">
       <div class="row">
         <div class="col-lg-9 mx-auto py-3">
           <div class="row">
             <div class="col-md-4 position-relative">
               <div class="p-3 text-center">
                 <h1 class="text-gradient text-dark">{{ num_topics }}</h1>
                 <h5 class="mt-3">Different topics</h5>
                 <p class="text-sm font-weight-normal">From politics to technology, art, sport or entertainment, all what might be interesting for you.</p>
               </div>
               <hr class="vertical dark">
             </div>
             <div class="col-md-4 position-relative">
               <div class="p-3 text-center">
                 <h1 class="text-gradient text-dark">{{ num_newspapers }}</h1>
                 <h5 class="mt-3">Articles</h5>
                 <p class="text-sm font-weight-normal">Create new article any time you want. Contribute to the world of news with us!</p>
               </div>
               <hr class="vertical dark">
             </div>
             <div class="col-md-4">
               <div class="p-3 text-center">
                 <h1 class="text-gradient text-dark">{{ num_publishers }}</h1>
                 <h5 class="mt-3">Publishers</h5>
                 <p class="text-sm font-weight-normal">Track all your articles in one place and also check other publishers publications.</p>
               </div>
             </div>
           </div>
         </div>
       </div>
     </div>
   </section>
 </div>
{% endblock %}

templates/agency/newspaper_confirm_delete.html
{% extends "base-fullscreen.html" %}
{% load crispy_forms_filters %}


{% block content %}

  <section>
    <div class="page-header min-vh-100">
      <div class="container">
        <div class="row">
          <div class="col-xl-6 col-lg-7 col-md-6 d-flex flex-column ms-auto me-auto ms-lg-auto me-auto">
            <div class="card d-flex blur justify-content-center shadow-lg my-sm-0 my-sm-6 mt-8 mb-5">
              <div class="card-header p-0 position-relative mt-n4 mx-3 z-index-2 bg-transparent">
                <div class="bg-gradient-dark shadow-dark border-radius-lg p-3">
                  <h3 class="text-white text-primary mb-0">Delete article?</h3>
                </div>
              </div>
              <div class="card-body">
                <p class="pb-3">
                  Please note that this action is irreversible, and article will be permanently deleted.
                </p>
                <form action="" method="post" novalidate>
                  {% csrf_token %}
                  <br>
                  <input type="submit" value="Yes, delete" class="btn btn-danger">
                  <a href="{{ view.get_success_url }}" class="btn btn-secondary">Cancel</a>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

{% endblock content %}

templates/agency/newspaper_detail.html
{% extends "base.html" %}

{% block content %}
  <section class="py-7 bg-light">
    <div class="container">
      <div class="row justify-content-center">
        <div class="text-lg-end">
          <button class="btn btn-secondary">
            <a href="{% url 'agency:newspaper-update' pk=newspaper.id %}" class="text-white">
              Edit
            </a>
          </button>
          <button class="btn btn-secondary">
            <a href="{% url 'agency:newspaper-delete' pk=newspaper.id %}" class="text-white">
            Delete
            </a>
          </button>
        </div>
        <div class="col-lg-9">
          <h1 class="text-center">
            {{ newspaper.title }}
          </h1>
          <ul class="text-center">
            {% for publisher in newspaper.publishers.all %}
              <p class="d-inline-block">{{ publisher.first_name }} {{ publisher.last_name }}</p>
            {% endfor %}
          </ul>
          <p class="lead text-lg-start">{{ newspaper.content }}</p>
        </div>
      </div>
    </div>
  </section>
{% endblock %}

templates/agency/newspaper_form.html
{% extends "base-fullscreen.html" %}
{% load crispy_forms_filters %}


{% block content %}

  <section>
    <div class="page-header min-vh-100">
      <div class="container">
        <div class="row">
          <div class="col-xl-6 col-lg-7 col-md-6 d-flex flex-column ms-auto me-auto ms-lg-auto me-auto">
            <div class="card d-flex blur justify-content-center shadow-lg my-sm-0 my-sm-6 mt-8 mb-5">
              <div class="card-header p-0 position-relative mt-n4 mx-3 z-index-2 bg-transparent">
                <div class="bg-gradient-dark shadow-dark border-radius-lg p-3">
                  <h3 class="text-white text-primary mb-0">{{ object|yesno:"Update,Create" }} article</h3>
                </div>
              </div>
              <div class="card-body">
                <p class="text-bold pb-3">
                  Please, {{ object|yesno:"modify,add new" }} article details in the fields below:
                </p>
                <form action="" method="post" novalidate>
                  {% csrf_token %}
                  {{form.title|as_crispy_field}}
                  <hr>
                  {{form.content|as_crispy_field}}
                  <hr>
                  <div>
                    <label class="me-3">Topic*</label>
                    {{form.topic}}
                  </div>
                  <hr>
                  <div>
                    <label>Publishers*</label>
                    {{form.publishers}}
                  </div>
                  {% if action == "create" %}
                    <input type="hidden" name="action" value="create">
                  {% else %}
                    <input type="hidden" name="action" value="update">
                  {% endif %}
                  <button type="submit" class="btn btn-info mt-3">Submit</button>
                  <input type="submit" formnovalidate name="cancel" value="Cancel" class="btn btn-secondary mt-3">
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

{% endblock content %}

templates/agency/newspaper_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block title %} Articles {% endblock %}

{% block content %}

  <header class="bg-gradient-dark">
    <div class="page-header min-vh-45" style="background-image: url('{{ ASSETS_ROOT }}/img/bg4.jpeg');">
      <span class="mask bg-gradient-dark opacity-6"></span>
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-lg-8 text-center">
            <h1 class="text-white mt-7">Explore recently published articles</h1>
          </div>
        </div>
      </div>
    </div>
  </header>

  <section class="py-5">
    <div class="container">
      <div class="row align-items-center">
        <div class="col-lg-10">
          <a href="{% url 'agency:newspaper-create' %}" class="btn btn-primary link-to-page">Create new article</a>
          {% if newspaper_list %}
            <ul>
              {% for newspaper in newspaper_list %}
                <li class="mt-3">
                  <a href="{% url 'agency:newspaper-detail' pk=newspaper.id %} ">
                    {{ newspaper.title }} ({{ newspaper.published_date }})
                    <a class="label p-1 text-white bg-gradient-faded-dark">{{ newspaper.topic.name }}</a>
                  </a>
                </li>
                <tr>
              {% endfor %}
            </ul>
          {% else %}
            <p>There haven't been published any articles yet</p>
          {% endif %}
        </div>
      </div>
    </div>
  </section>
  {% block pagination %}
    {% include "includes/pagination.html" %}
  {% endblock %}
{% endblock %}

templates/agency/publisher_detail.html
{% extends "base.html" %}

{% block content %}
  <section class="py-7 bg-light">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-lg-9">
          <h3 class="text-center">
            {{ publisher.first_name}} {{ publisher.last_name }}
            <p> (username: {{ publisher.username }})</p>
          </h3>
          <br>
            <h4>Published articles</h4>
            {% for newspaper in publisher.newspapers.all %}
            <hr>
            <p class="text-black"><strong>Title:</strong> {{ newspaper.title }}</p>
            <p><strong>Date of publishing:</strong> {{ newspaper.published_date }}</p>
            <p class="text-muted"><strong>Topic:</strong> {{newspaper.topic.name}}</p>
          {% empty %}
            <p>This author haven't published any articles yet!</p>
          {% endfor %}
        </div>
      </div>
    </div>
  </section>
{% endblock %}

templates/agency/publisher_list.html
{% extends "base.html" %}

{% block title %} Publishers {% endblock %}

{% block content %}

  <header class="bg-gradient-dark">
    <div class="page-header min-vh-45" style="background-image: url('{{ ASSETS_ROOT }}/img/bg5.jpg');">
      <span class="mask bg-gradient-dark opacity-6"></span>
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-lg-8 text-center mx-auto my-auto">
            <h1 class="text-white">Check our team</h1>
          </div>
        </div>
      </div>
    </div>
  </header>
    <section class="py-5">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-lg-10">
          {% if publisher_list %}
            <table class="table">
              <tr>
                <th>ID</th>
                <th>Username</th>
                <th>First name</th>
                <th>Last name</th>
                <th>Years of experience</th>
              </tr>
              {% for publisher in publisher_list %}
                <tr>
                  <td>{{ publisher.id }}</td>
                  <td><a href="{{ publisher.get_absolute_url }}">{{ publisher.username }} {% if user == publisher %} (Me){% endif %}</a></td>
                  <td>{{ publisher.first_name }}</td>
                  <td>{{ publisher.last_name }}</td>
                  <td>{{ publisher.years_of_experience }}</td>
                </tr>
                {% endfor %}
            </table>
          {% else %}
            <p>There are no publishers in the service.</p>
          {% endif %}
        </div>
      </div>
    </div>
  </section>
  {% block pagination %}
    {% include "includes/pagination.html" %}
  {% endblock %}
{% endblock %}

templates/agency/topic_confirm_delete.html
{% extends "base-fullscreen.html" %}
{% load crispy_forms_filters %}


{% block content %}

  <section>
    <div class="page-header min-vh-100">
      <div class="container">
        <div class="row">
          <div class="col-xl-6 col-lg-7 col-md-6 d-flex flex-column ms-auto me-auto ms-lg-auto me-auto">
            <div class="card d-flex blur justify-content-center shadow-lg my-sm-0 my-sm-6 mt-8 mb-5">
              <div class="card-header p-0 position-relative mt-n4 mx-3 z-index-2 bg-transparent">
                <div class="bg-gradient-dark shadow-dark border-radius-lg p-3">
                  <h3 class="text-white text-primary mb-0">Delete topic?</h3>
                </div>
              </div>
              <div class="card-body">
                <p class="pb-3">
                  Please note that this action is irreversible, and topic will be permanently deleted.
                </p>
                <form action="" method="post" novalidate>
                  {% csrf_token %}
                  <br>
                  <input type="submit" value="Yes, delete" class="btn btn-danger">
                  <a href="{{ view.get_success_url }}" class="btn btn-secondary">Cancel</a>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

{% endblock content %}

templates/agency/topic_form.html
{% extends "base-fullscreen.html" %}
{% load crispy_forms_filters %}


{% block content %}

  <section>
    <div class="page-header min-vh-100">
      <div class="container">
        <div class="row">
          <div class="col-xl-6 col-lg-7 col-md-6 d-flex flex-column ms-auto me-auto ms-lg-auto me-auto">
            <div class="card d-flex blur justify-content-center shadow-lg my-sm-0 my-sm-6 mt-8 mb-5">
              <div class="card-header p-0 position-relative mt-n4 mx-3 z-index-2 bg-transparent">
                <div class="bg-gradient-dark shadow-dark border-radius-lg p-3">
                  <h3 class="text-white text-primary mb-0">{{ object|yesno:"Update,Create" }} topic</h3>
                </div>
              </div>
              <div class="card-body">
                <p class="pb-3">
                  Please, {{ object|yesno:"modify,add new" }} topic in the field below:
                </p>
                <form action="" method="post" novalidate>
                  {% csrf_token %}
                  <div class="input-group input-group-outline mb-3">
                    <a class="text-bold">{{form.name}}</a>
                  </div>
                  <br>
                  {% if action == "create" %}
                    <input type="hidden" name="action" value="create">
                  {% else %}
                    <input type="hidden" name="action" value="update">
                  {% endif %}
                  <button type="submit" class="btn btn-info">Submit</button>
                  <input type="submit" formnovalidate name="cancel" value="Cancel" class="btn btn-secondary">
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

{% endblock content %}

templates/agency/topic_list.html
{% extends "base.html" %}

{% block title %} Topics {% endblock %}

{% block content %}

  <header class="bg-gradient-dark">
    <div class="page-header min-vh-45" style="background-image: url('{{ ASSETS_ROOT }}/img/bg1.jpeg');">
      <span class="mask bg-gradient-dark opacity-6"></span>
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-lg-8 text-center mx-auto my-auto">
            <h1 class="text-white">Choose any topic</h1>
            <p class="lead mb-4 text-white opacity-8">We’re constantly trying to express ourselves and actualize our ideas</p>
          </div>
        </div>
      </div>
    </div>
  </header>

  <section class="py-5">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-lg-4">
          {% if topic_list %}
            <table class="table">
              <tr>
                <th>ID</th>
                <th>Name</th>
              </tr>
              {% for topic in topic_list %}
                <tr>
                  <td>
                    {{ topic.id }}
                  </td>
                  <td>
                    {{ topic.name }}
                  </td>
                  <td>
                    <a href="{% url 'agency:topic-update' pk=topic.id %}">
                      <i class="fas fa-edit"></i>
                    </a>
                  </td>
                  <td>
                    <a href="{% url 'agency:topic-delete' pk=topic.id %}">
                      <i class="far fa-trash-alt"></i>
                    </a>
                  </td>
                </tr>
              {% endfor %}
            </table>
          {% else %}
            <p>There were no topics discussed yet.</p>
          {% endif %}
          <a href="{% url 'agency:topic-create' %}" class="btn btn-primary link-to-page">Create new topic</a>
        </div>
      </div>
    </div>
  </section>
{% endblock %}