agency/urls.py
from django.urls import path
from agency.views import (
    index,
    TopicListView,
    NewspaperListView,
    PublisherListView,
    NewspaperDetailView,
    PublisherDetailView,
    TopicCreateView,
    TopicUpdateView,
    TopicDeleteView,
    NewspaperCreateView,
    NewspaperUpdateView,
    NewspaperDeleteView
)

urlpatterns = [
    path("", index, name="index"),
    path(
        "topics/",
        TopicListView.as_view(),
        name="topic-list",
    ),
    path(
        "topics/create/",
        TopicCreateView.as_view(),
        name="topic-create",
    ),
    path(
        "topics/<int:pk>/update/",
        TopicUpdateView.as_view(),
        name="topic-update",
    ),
    path(
        "topics/<int:pk>/delete/",
        TopicDeleteView.as_view(),
        name="topic-delete",
    ),
    path(
        "articles/",
        NewspaperListView.as_view(),
        name="newspaper-list",
    ),
    path(
        "articles/create/",
        NewspaperCreateView.as_view(),
        name="newspaper-create",
    ),
    path(
        "articles/<int:pk>/update/",
        NewspaperUpdateView.as_view(),
        name="newspaper-update",
    ),
    path(
        "articles/<int:pk>/delete/",
        NewspaperDeleteView.as_view(),
        name="newspaper-delete",
    ),
    path(
        "articles/<int:pk>/",
        NewspaperDetailView.as_view(),
        name="newspaper-detail",
    ),
    path(
        "publishers/",
        PublisherListView.as_view(),
        name="publisher-list",
    ),
    path(
        "publishers/<int:pk>/",
        PublisherDetailView.as_view(),
        name="publisher-detail",
    ),
]

app_name = "agency"

newspaper_agency/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
   path("admin/", admin.site.urls),
   path("", include("agency.urls", namespace="agency")),
   path('accounts/', include('django.contrib.auth.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/includes/navigation.html
{% load crispy_forms_filters %}
<div class="container position-sticky z-index-sticky top-0">
  <div class="row">
    <div class="col-12">
      <nav class="navbar navbar-expand-lg  blur border-radius-xl mt-4 top-0 z-index-3 shadow position-absolute my-3 py-2 start-0 end-0 mx-4">
        <div class="container-fluid px-0">
          <div class="nav-item my-auto ms-3 ms-lg-0">
            <form action="" method="get">
              {{ search_form|crispy }}
            </form>
          </div>
          <ul class="navbar-nav ms-auto">
            <a class="nav-link ps-2 d-flex cursor-pointer align-items-center" href="{% url 'agency:index' %}">Home</a>
            <a class="nav-link ps-2 d-flex cursor-pointer align-items-center" href="{% url 'agency:topic-list' %}">Topics</a>
            <a class="nav-link ps-2 d-flex cursor-pointer align-items-center" href="{% url 'agency:newspaper-list' %}">Articles</a>
            <a class="nav-link ps-2 d-flex cursor-pointer align-items-center" href="{% url 'agency:publisher-list' %}">Publishers</a>
            {% if user.is_authenticated %}
              <li class="nav-item my-auto ms-3 ms-lg-0">
                <a href="{% url 'logout'%}" target="_blank" class="btn btn-sm  bg-gradient-grey  mb-0 me-1 mt-2 mt-md-0">Logout</a>
              </li>
            {% else %}
              <li class="nav-item my-auto ms-3 ms-lg-0">
                <a href="{% url 'login'%}" target="_blank" class="btn btn-sm  bg-gradient-info  mb-0 me-1 mt-2 mt-md-0">Login</a>
              </li>
            {% endif %}
          </ul>
        </div>
      </nav>
    </div>
  </div>
</div>

templates/includes/pagination.html
{% load query_transform %}
<div class="container">
  <div class="fixed-bottom">
    <div class="row justify-content-sm-center">
      <div class="col-lg-2">
        {% if is_paginated %}
          <ul class="pagination">
            {% if page_obj.has_previous %}
              <li class="btn btn.text-center btn-dark btn-round me-2">
                <a href="?{% query_transform request page=page_obj.previous_page_number %}" class="text-white bg-transparent">prev</a>
              </li>
            {% endif %}
            <li class="page-item active me-2">
              <span class="text-black bg-transparent">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
            </li>
            {% if page_obj.has_next %}
              <li class="btn btn.text-center btn-dark btn-round me-2">
                <a href="?{% query_transform request page=page_obj.next_page_number %}" class="text-white bg-transparent">next</a>
              </li>
            {% endif %}
          </ul>
        {% endif %}
      </div>
    </div>
  </div>
</div>